# Generated by Django 2.2 on 2020-08-29 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poll',
            old_name='poll',
            new_name='text',
        ),
    ]
